"""update models

Revision ID: 46bf782288f0
Revises: 9f5f422a822c
Create Date: 2026-03-13 17:29:13.346784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46bf782288f0'
down_revision: Union[str, Sequence[str], None] = '9f5f422a822c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shoots', sa.Column('notify_before_2hr', sa.Boolean(), nullable=True))
    op.add_column('shoots', sa.Column('notify_before_1hr', sa.Boolean(), nullable=True))
    op.add_column('uploads', sa.Column('notify_before_2hr', sa.Boolean(), nullable=True))
    op.add_column('uploads', sa.Column('notify_before_1hr', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('uploads', 'notify_before_1hr')
    op.drop_column('uploads', 'notify_before_2hr')
    op.drop_column('shoots', 'notify_before_1hr')
    op.drop_column('shoots', 'notify_before_2hr')
    # ### end Alembic commands ###
