"""Updated models

Revision ID: 9f5f422a822c
Revises: 4a29c1e7ff73
Create Date: 2026-03-02 21:30:29.312509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f5f422a822c'
down_revision: Union[str, Sequence[str], None] = '4a29c1e7ff73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shoots', sa.Column('review_generated', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shoots', 'review_generated')
    # ### end Alembic commands ###
