"""update models

Revision ID: f1c726bcb08c
Revises: d0ccf5f8d27a
Create Date: 2026-03-17 16:43:33.748041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1c726bcb08c'
down_revision: Union[str, Sequence[str], None] = 'd0ccf5f8d27a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collab_notifications',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('influencer_id', sa.String(), nullable=False),
    sa.Column('brand_name', sa.String(), nullable=False),
    sa.Column('person_name', sa.String(), nullable=False),
    sa.Column('person_phone', sa.String(), nullable=False),
    sa.Column('person_email', sa.String(), nullable=True),
    sa.Column('budget', sa.Integer(), nullable=True),
    sa.Column('business_info', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['influencer_id'], ['influencers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collab_notifications_id'), 'collab_notifications', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_collab_notifications_id'), table_name='collab_notifications')
    op.drop_table('collab_notifications')
    # ### end Alembic commands ###
